version: '3.1'

services:
  #usuario: root
  #senha: admin
  db:
    image: mysql
    ports: 
      - 3306:3306
    volumes: 
      - ./:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    networks:
    - main
  php:
    build: './'
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html/
    links:
      - db
    networks:
    - main
networks:
  main:
    driver: bridge